### PR TITLE
Minimum viable products and hacking it

### PR DESCRIPTION
**Pull request by janiceli16**
hi team - can you please let me know if i'm missing anything re: MVPs?
@wendyeatworld @caroljpak @AmyLingLin @jfmos @kferris16 @agould65

### CODE REVIEW

**Comment by agould65** [comment]
Hey looks good to me @janiceli16 :+1:

**Comment by kferris16** [comment]
Great job @janiceli16   One other takeaway that I recall from Professor Bell is that the word "product" often carries with it a lot of red tape, and that managers are better served by referring to MVPs as "experiments".  This simple change in terminology can significantly lessen the time it takes to develop an MVP.

**Comment by jfmos** [comment]
@janiceli16 it's the nices page with probably have ;) love the doughnuts. I think just one small think we can mention from the class is to organize terminology seems MVP supports agile programming. I also found this nice explanation of differencethat was @mentioned http://agilesoftwareengineer.com/2013/08/28/minimum-viable-product-vs-minimum-marketable-product/

**Comment by wendyxs** [comment]
Looks good @janiceli16 !

**Comment by janiceli16** [comment]
@jfmos @kferris16 thanks for the great feedback! i've incorporated changes into the markdown report with your suggestions.

**Comment by caroljpak** [comment]
I now want a donut :+1:

**Comment by AmyLingLin** [comment]
:+1:

**Pull request merged**
