### PR TITLE
Create Tips of Starting a Tech Startup.md

### PR DESCRIPTION
**Pull request by jfmos**
@AmyLingLin I pulled it in the caroljpak fork for you
@janiceli16 @agould65 @caroljpak @wendyeatworld Please add comments for Amy, so we can finish the project

### CODE REVIEW

**Comment by jfmos** [comment]
@AmyLingLin  Please change the name of the file to .md It would be great if you could add bit of formating + some picture and links as per other entries we have

**Comment by AmyLingLin** [comment]
Thank you! @jfmos

**Comment by janiceli16** [comment]
@AmyLingLin agreed with jfmos, just needs a bit more formatting, maybe space things out to be more visually pleasing.

**Comment by AmyLingLin** [comment]
Hey how to add pic?

**Comment by jfmos** [comment]
http://www.w3schools.com/html/html_basic.asp
use IMG for pics
A for links 
You need to find a picture in the Internet to link it to img

**Comment by AmyLingLin** [comment]
Thank you @janiceli16 @janiceli16 Is it ready to go?

**Comment by caroljpak** [comment]
Looks good! :+1:

**Comment by AmyLingLin** [comment]
Thank you! @caroljpak

**Pull request merged**
