### PR TITLE
How much should and engineer cost

### PR DESCRIPTION
**Pull request by agould65**
Hey guys, let me know what you think of the my file on engineer hiring options and remuneration

### CODE REVIEW

**Comment by jfmos** [comment]
@agould65  looks fine. Pls. check the name of the file(lack of .md - can't preview) and branch (and-->an) HAve a good evening

**Comment by kferris16** [comment]
@agould65 Content is great.  Echoing Jan's comment, change the file type to .md.  Also, use the number sign (#) to denote headers rather than "h1", "h2" etc.  More info here:

https://help.github.com/articles/markdown-basics/

**Comment by wendyxs** [comment]
@agould65 looks good! One thing I would add in addition is that shops may be able to offer more continuity, but full time is probably the best option if continuity is really important.

**Comment by janiceli16** [comment]
@agould65 looks great! a few more bullets to consider adding:

contractors:
-good for simpler/1-time projects
-unique person/talent

peter also broke down per hour how much each category would cost, this could be helpful:
full-time: $95/hour
dev shop: $250/hour
contractor: $120-150/hour

**Comment by agould65** [comment]
Thanks for the feedback guys, have incorporated the suggested changes. Let me know if ok to merge!

Alex

**Comment by caroljpak** [comment]
Think you have everything covered! :+1:

**Comment by kferris16** [comment]
Looks good to me :+1:

**Comment by AmyLingLin** [comment]
:+1::smile:

**Pull request merged**
