### PR TITLE
How to hire a great engineer

### PR DESCRIPTION
**Pull request by wendyxs**
I need help with how to meet a great engineer section because I missed it in class.  Let me know what you guys think! @janiceli16 @caroljpak @AmyLingLin @kferris16 @jfmos @agould65

### CODE REVIEW

**Comment by janiceli16** [comment]
hi @wendyeatworld, here are my notes for how to meet a great engineer:
1) go to tech meetups and meet as many nerdy, technical people are you can! try to find one who shares and believes in your business mission
2) hackathons - you can pitch your ideas to developers and designers there. make sure you're not at a hackathon where it's heavily populated by business people
3) startup fairs and recruiting events
4) try to learn programming yourself and ask a developer (at a meetup / fair, etc.) if they can give you some inside tips on learning how to code

**Comment by wendyxs** [comment]
@janiceli16 thank you!

**Comment by wendyxs** [comment]
@janiceli16 @caroljpak @AmyLingLin @kferris16 @jfmos @agould65 feel free to add other comments, otherwise I think I am ready to merge.

**Comment by jfmos** [comment]
@wendyeatworld looks, great. You can also add that is beneficial to check on github whether he contributed to anything meaningful...
Also you named it how to hire the good engineer. Maybe you want to add something about the interview process? the questions to ask were e.g. do you run tests? how do you run those do you do BSD Which framework do you use etc...

**Comment by kferris16** [comment]
Great job on this thorough and detailed write-up, @wendyeatworld.  One suggestion:  I would note that as a manager you should look for developers who have made meaningful open-source contributions.

**Comment by jfmos** [comment]
@wendyeatworld Amazing job, from my POV we are done here

**Comment by wendyxs** [comment]
@jfmos @kferris16 thanks! I added the open-source point.

**Comment by caroljpak** [comment]
Love it! 
I would also hope the developer is pleasant to work with and reliable, especially if working remotely. 
The pic is the best part :+1:

**Comment by agould65** [comment]
Great work Wendy, love the photo too. Good to merge! :+1:

**Pull request merged**
