### PR TITLE
Lean software development feedback

### PR DESCRIPTION
**Pull request by kferris16**
@caroljpak @janiceli16 @wendyeatworld @AmyLingLin @jfmos @agould65  Guys, please take a look at my file on lean software development and let me know if you have any suggestions.  Thanks!

### CODE REVIEW

**Comment by agould65** [comment]
Hi Kyle, your file looks good to me - the image is interesting, it could maybe do with a title to explain what it is though?

**Comment by jfmos** [comment]
@kferris16  makes sense, do you think of any example that could illustrate lean?

**Comment by kferris16** [comment]
Thanks @agould65, I've added a description explaining the lean "mind map".

**Comment by kferris16** [comment]
Good suggestion @jfmos.  I've added an example from the book "Implementing Lean Software Development".

**Comment by wendyxs** [comment]
@kferris16 looks good!

**Comment by janiceli16** [comment]
@kferris16 solid content, looks good to me!

**Comment by caroljpak** [comment]
:+1: great content and format! I think CBS offers a course on lean by Steve Blank if you want to learn more!

**Comment by agould65** [comment]
@kferris16 Looks good to me also :+1:

**Pull request merged**
