### PR TITLE
How to spend resources on development efficiently

### PR DESCRIPTION
**Pull request by jfmos**
@caroljpak @janiceli16 @AmyLingLin @wendyeatworld @kferris16 @agould65 
Please kindly check and provide a feedback
Thanks

### CODE REVIEW

**Comment by kferris16** [comment]
Great job @jfmos  One very minor nitpick about formatting:  items 2-5 are indented further to the right than item 1.

**Comment by wendyxs** [comment]
@jfmos good job! The only thing you could maybe add is a picture and a link; I think we need to include one per the assignment instructions to show off our fancy html know-how :wink:

**Comment by janiceli16** [comment]
@jfmos great job! for controlling, consider adding a line about a scrum master, someone who facilitates the process of lean software development, managing the backlog and removing impediments to good code. some more details here:
http://scrummethodology.com/the-scrummaster-role/

**Comment by caroljpak** [comment]
Great job! We also talked about the Kanban board that tracks the different tasks under each phase of 'to-do,' 'doing,' 'QA,' and 'done' on platforms such as Trello. These boards would be useful in monitoring backlog and syncing and communicating with your developers. :+1:

**Comment by jfmos** [comment]
@kferris16 thanks - I've seen the indendent problem- it doesn't solve here - it's some formatting that github applies without my html tags 
@janiceli16 thanks for the scrum, see updated
@caroljpak many thanks for trello comment - it's done
@wendyeatworld added a picture and link

**Comment by AmyLingLin** [comment]
:smile_cat:

**Pull request merged**
