### PR TITLE
Using GitHub

### PR DESCRIPTION
**Pull request by jfmos**
@caroljpak I think I put my comment directly in the code. Thanks for upating ;) On my side seems we are ready to pull

### CODE REVIEW

**Comment by caroljpak** [comment]
@kferris16 @janiceli16 @wendyeatworld @AmyLingLin @jfmos @agould65 
Please let me know if you have any suggestions! Thanks all :smile:

**Comment by agould65** [comment]
Looks good to me! :+1:

**Comment by wendyxs** [comment]
:+1:

**Comment by AmyLingLin** [comment]
:+1:

**Pull request merged**
